# Generated by Django 6.0.2 on 2026-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('student_class', models.CharField(choices=[('ONE', 'Class 1'), ('TWO', 'Class 2'), ('THREE', 'Class 3'), ('FOUR', 'Class 4'), ('FIVE', 'Class 5'), ('SIX', 'Class 6'), ('SEVEN', 'Class 7'), ('EIGHT', 'Class 8'), ('NINE', 'Class 9'), ('TEN', 'Class 10')], default='ONE', max_length=10)),
            ],
        ),
    ]
