# Generated by Django 6.0.2 on 2026-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others ')], max_length=1)),
                ('subjects', models.CharField(choices=[('MATH', 'Mathematics'), ('SCI', 'Science'), ('ENG', 'English'), ('NEP', 'Nepali'), ('SOC', 'Social Studies '), ('ECO', 'Economics')], max_length=10)),
                ('salary', models.CharField()),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
