# Generated by Django 6.0.2 on 2026-02-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
