# Generated by Django 6.0.2 on 2026-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
    ]
