# Generated by Django 6.0.2 on 2026-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_student_photos_teacher_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photos',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photos',
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('ONE', 'Class 1'), ('TWO', 'Class 2'), ('THREE', 'Class 3'), ('FOUR', 'Class 4'), ('FIVE', 'Class 5'), ('SIX', 'Class 6'), ('SEVEN', 'Class 7'), ('EIGHT', 'Class 8'), ('NINE', 'Class 9'), ('TEN', 'Class 10')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('SCI', 'Science'), ('ENG', 'English'), ('NEP', 'Nepali'), ('SOC', 'Social Studies'), ('ECO', 'Economics')], max_length=50),
        ),
    ]
